### ISSUE TITLE
2.10.10 Doesn't detect additional file extensions

### ISSUE THREAD

**Issue by fosam** [rowrawer/stream-detector#135]
Hi

The latest version doesn't detect additional file extensions like flv, i switched back to 2.10.9 and it works as it should, there must be a bug in the latest version

**Comment by rowrawer** [comment]
You're absolutely right. I'll push a fix soon.

**Comment by fosam** [comment]
By the way, what's the best way to update the extension without re-installing it and re-doing all the user settings if you know what i mean?

**Comment by fosam** [comment]
I mean updating the extension from a specific version to the latest one, like from 2.10.9 to 2.10.10

I had to delete 2.10.9 and install 2.10.10 manualy from this repo

**Comment by rowrawer** [comment]
Firefox should download the latest version automatically. If you're using anything else, you're on your own. Though I don't see why you would need to delete everything and reset your settings, you should be able to replace/overwrite the addon without having to remove it.

In any case, this issue should now be fixed in v2.10.11.

**Comment by fosam** [comment]
Thanks!

**Comment by fosam** [comment]
I forgot to mention that i'm on Chrome, i tried to replace the extention folder with the new files, but the extension disappears, so i had to load it unpacked again which removes all the settings

**Comment by rowrawer** [comment]
That's annoying, but not particularly surprising. My honest advice would be to not use Chrome unless you absolutely have to.

**Comment by Dean-Corso** [comment]
Hi guys,

I also installed latest version today (2.10.8 to 2.10.11) in Brave browser too. I'am using same settings as before (just do copy paste of my custom extensions & header types and settings same hooks to enable etc). Now on first test I'am using both extension versions at same time to see whether they also really work same before I remove the old unpacked version and I get some difference results back. In case of mp4 extension files I got nothing in new version anymore but I got results in both versions for mp3 files. After short testing around I found out that I have NOW to disable the option "ignore direct links to media files" what I have still disables in the old version called "ignore direct links to video/audio files". Why I need to enable it now? Anyway, all in all its still working and just need to unhook this one option now to make it work. 

By the way, so I have a small new request about using custom content type headers. I would like to have a new field where I can enter any custom content file headers I want to exclude from logging. In case of HLS streams sites using diffrent types of extensions like mp4 for segment files and thats a problem because I don't want to get logged all single segment files. Normaly I have added the mp4 extension in my custom list to scan for and log it but this also happens now with mpeg-ts files using same mp4 extension. My idea now is pretty simple by adding a exclude field for custom content type header. In case of mpeg-ts the content type header is "video/MP2T" for example and this I want to exclude. In case of real mp4 files the type header is "video/mp4". So to make it short...we need to have an exclude field for content-types in headers. Lets say I have added mp4 in additional file extensions field then your tool should scan for all mp4 file extensions and log it into popup window as it does already. The second field content-type-headers you need to check too to find matching types in files and log them. Now comes the new field to exclude types. When your tool does find a file with extension mp4 then you need to check the exclude types whether its matching with the found extension and if YES then you DO NOT log it. You know what I mean right. So I think its pretty good idea to prevent logging everything in cases when files using same file extensions = problem, but then you have the extra check with the new type excludes to make another check. Just think about it. I like that idea.

**Comment by rowrawer** [comment]
Thank you for your in-depth feedback yet again.

>I also installed latest version today (2.10.8 to 2.10.11) in Brave browser too. I'am using same settings as before (just do copy paste of my custom extensions & header types and settings same hooks to enable etc). Now on first test I'am using both extension versions at same time to see whether they also really work same before I remove the old unpacked version and I get some difference results back. In case of mp4 extension files I got nothing in new version anymore but I got results in both versions for mp3 files. After short testing around I found out that I have NOW to disable the option "ignore direct links to media files" what I have still disables in the old version called "ignore direct links to video/audio files". Why I need to enable it now? Anyway, all in all its still working and just need to unhook this one option now to make it work.

I'm not sure what you're saying - does that option have the opposite effect now? Ignoring media files detects them? Or are you noting the slight change in wording?

As for your request, I think instead of cluttering up the options with more textboxes, I'll simply implement content-type header filtering to the blacklist. I thought it already filtered through headers, but apparently not.

**Comment by Dean-Corso** [comment]
Hello again rowrawer,

no problem so I try to help a little if I can. Yes, it seems now to do some opposite thing. As I said, I'am using exact same settings in both versions (for testing I don't use any custom extensions & type headers).

I have test it again now trying to use same settings / enabled and test it with websites using mp4, m4a & HLS playlist (m3u8).
2.10.8
2.10.11

So at the moment I get same results when I have checked the options "ignore direct links to media". Now I get nothing for mp4, m4a but I get HLS playlist stream link logged (no TS segments). All fine so far in both versions with same settings. Now I just add a custom extension mp4 & m4a and try it again and right now I don't get any mp4 file logged in version 2.10.11 but in 2.10.8 I get it logged. Thats the difference now and to make it work in version 2.10.11 too I need now to uncheck the "ignore direct links to media" option. Maybe you did something wrong as you renames this option or anything etc. Strange thing is that this not happens in case of m4a extension. In case of HLS it also works diffrent now when using extension mp4 in custom header. In the new version I don't get logged TS segments but in the old version. Somehow both versions working diffrently a little. Just test it too a little.

So I think you need to add some more smart options for the users who want to use your tool. Having the custom extension field and the custom content type header field are very helpfully and now you just need to add another exclude or blacklist field for content type headers or maybe you can make a new field to put content type header into and allow or block them etc you know, because extensions XY can use different content-type-headers and I as user would like to specify my custom settings so that just the URLs get logged I also want to get logged. Anyway, so you know what I mean. Just try to add a new setting (blacklist / exclude etc) you think that would work best and then release a new version to check this out in real action and I send another feedback. Thanks for reading and keep going with your tool.

PS: At the moment your tool works so that all custom extension & content type headers are checked independently from each other. When a custom extension does match like mp4 then your tool will log the URL and if the custom content-type-header does match in any URL then you tool will log it too. All fine so far. Now we need some another option field etc to specify our URLs / matches by using a exclude content-types for specific extensions. Lets say any extension file I want to get log is using 4 different type-headers but I wanna just get logged only 2 of them and then I need to specify the types I don't wanna have. Alright, I think you know what I mean. Just remember in some specific cases websites using fake & custom extensions & content-type-headers and it would be nice to be prepared for this and make own custom scan rules when using your tool.

**Comment by rowrawer** [comment]
You're right, thanks to your detailed feedback I think I was able to fix the issue. Should be fine in the next update.

As for your suggestion, I think that might get too confusing for some users. Unless others also want such in-depth customization, I will go ahead with implementing content-type filtering to the existing blacklist in the next update as well - might help with your issue without cluttering up the options.

**Comment by Dean-Corso** [comment]
Hi,

thanks for the update. In the "the_stream_detector-2.10.12.crx" I get a error after loading the unpacked folder into Chrome/Brave about some....
```
Manifest version 2 is deprecated, and support will be removed in 2023. 
See https://developer.chrome.com/blog/mv2-transition/ for more details.

{"name":"The Stream Detector","description":"__MSG_extText__","manifest_version":2,"default_locale":"en","permissions":["<all_urls>","clipboardWrite","downloads","notifications","storage","tabs","webRequest"],"background":{"page":"background.html"},"icons":{"16":"img/icon-dark-16.png","48":"img/icon-dark-48.png","96":"img/icon-dark-96.png"},"commands":{"open-popup":{"description":"__MSG_openPopup__"}},"options_ui":{"open_in_tab":true,"page":"options.html"},"browser_action":{"default_title":"The Stream Detector","default_popup":"popup.html","default_icon":{"16":"img/icon-dark-16.png","48":"img/icon-dark-48.png"},"theme_icons":[{"dark":"img/icon-dark-96.png","light":"img/icon-light-96.png","size":96},{"dark":"img/icon-dark-48.png","light":"img/icon-light-48.png","size":48},{"dark":"img/icon-dark-16.png","light":"img/icon-light-16.png","size":16}]},"version":"2.10.12"}
```
...maybe you can fix this in next release. Alright, I have checked your new version and it seems to work so far. I just unchecked the ignore direct links to media files and it works and with checked it does not log direct media files if I don't hava anything set into custom fields. All good now. Also tried the blacklist field to disable some file headers and its working too. I think all in all you did it well done now. 😃 I don't see any issues at the moment except that Chrome error above about manifest version. I will keep testing & checking your tool and send some more feedbacks later about possible found problems or new ideas etc. Thank you rowrawer.

**Comment by rowrawer** [comment]
That can't really be fixed easily, it's a non-Firefox browser problem.

Glad everything seems to be working. New ideas aren't particularly necessary but feel free.

**Comment by Dean-Corso** [comment]
It can be fixed for Chrome extension? Does it mean I can just use your extension for Chrome only til 2023? Or is it just a error I can ignore and your extension keeps working in Chrome?

I forgot to ask you one more thing about a tiny new request. Could you maybe add a size limitation for found file to not log them? Lets say I don't wanna get logged files under 100 KB or 1 MB etc something like that to customize it. But could be a problem when you add this feature and use it for all. So files like playlists can be small and files like MP4 can be large. Is it possible to make some custom size limit rules for specific file extensions etc? Just a  idea only maybe no must have feature etc you know.

**Comment by rowrawer** [comment]
I haven't really looked into it - I'm not particularly interested in maintaining Chrome support, especially since manifest v3 seems quite limiting. But we'll see. 2023 is still quite far away.

I'll consider adding a size limit to non-playlist files, that seems reasonable.

**Comment by Dean-Corso** [comment]
Hhmm, so you mean you will just continue your tool for Firefox only when that manifest v3 is out etc? Just don't understand it yet correctly what it means for me as user. Does your Chrome/Brave extension is still working then or not or just the old versions or how should I understand it? So mostly I'am using your tool in Brave browser. Would be really bad if it would no more work in 2023.

Ah ok about size limit. Sounds good.

**Comment by rowrawer** [comment]
Google are forcing the new manifest format as of 2023, which means that (if I don't migrate to version 3 in the meantime) the addon will stop working on an up-to-date Chrome installation. No clue what other Chrome-based browsers are planning on doing.

**Comment by Dean-Corso** [comment]
Oh god! I really hate that stupid forcing changes from the Chrome guys. Hhmm! Its same like with those flag removings (Enable Incognito brand consistency in desktop) to no more allow using custom themes in incognito mode since a longer while now. Alright, lets see what happens 2023 whether its then still working with any Brave browser or not. Would be really bad if not.

**Comment by rowrawer** [comment]
Minimum file size limit has now been added as of v2.10.13.
