### ISSUE TITLE
I like the old version better, can that option be added back

### ISSUE THREAD

**Issue by JerryT2020** [rowrawer/stream-detector#14]
**_Hello, I like stream detector the way it was few day's ago ._**

Right click and have it there instead on top of page.

Also the popup's of the streams detected now stack up
all over my screen if it detects more streams on one page.
![Snap 2020-06-06 at 08 01 41](https://user-images.githubusercontent.com/66508125/83937626-bb8e7b00-a7ce-11ea-81b8-0c377faacb36.jpg)

It was better before, detect one, fade out and show the next,
at the same spot bottom right.. not blocking the whole screen,
as also the present menu on top right does.

I liked the previous better implementation better.
Maybe it can be select-able as an option 

Hope i made it understandable ..

**For the rest, great add-on..** ( i also hope, like a previous comment,
it will be coming to Chrome also, if not, i can live with it )

Best regards !!
- [ ]

**Comment by rowrawer** [comment]
Hello,

If the notifications annoy you, you can turn them off in the options. I think having one notification per every detected stream is better than just one general notification, but I'll consider switching them back to their old behavior - I can see how they could become impractical.

As for the implementation, the current one is a lot better than the previous one in many ways. I have removed everything related to the old functionality and reworked a lot of the code specifically because of how bad the previous implementation was - I'm sure you'd get used to it sooner rather than later if you gave it a chance.

If you still find yourself unable to use the new version for whatever reason, you can always [install the old version again](https://addons.mozilla.org/en-US/firefox/addon/hls-stream-detector/versions/) and disable automatic updates. It should still work fine.

Porting the extension to Chrome wouldn't be too hard to do, I think, but I don't feel like paying Google $5 to be able to publish this thing in their Web Store at this point in time.


All the best.

**Comment by rowrawer** [comment]
The notifications have now been tamed as of v2.0.1.

**Comment by JerryT2020** [comment]
Hello, thanks for the reply..

About the pop-up notifications..  as i sugested, maybe include
an option how they apear on screen.. like the previous, or like
the new version.  

**_But at the moment, it's seems they apear like in the previous version,
not covering the right side of my screen..  It's better this way.._**

Another sugestion would be to limit the displayed caracters
in the pop-up window so the pop-up window ( down right)
isn't to wide. and maybe a little higher, atleast above the 
standard hight of the taskbar. 

If the pop-up is there, i can't click any icons i have there,
until the pop-up has disapeared..
My taskbasr is set to auto-hide.. with the pop-up so
low, it doesn't come up or i have to go past it to the left,
to activate it.

As the links  can be selected after the detection from the menu
at the top bar, the full lenght of the url is not needed in the
pop-up notification, i think.

Having it in the " right click " menu, worked faster for me, then
going to the top of my screen to select it.

But, as you sayd, ill give it a go.. or just go back to the
previous version..

Anyway's, it's a great add-on.. good to have available and
much apreciated..

All coments are meant as a positive 

Best regards .

**Comment by rowrawer** [comment]
Hi, thanks for your feedback. I'm pretty sure you're confusing the popup (which is what the main interface is now called) with notifications - if you want to get rid of the notifications in the bottom right corner of the screen, you can disable them in the addon options and you should be good to go. 


All the best.
