### ISSUE TITLE
Only show certain number of latest entries shows nothing

### ISSUE THREAD

**Issue by AndroKev** [rowrawer/stream-detector#144]
hello,

when i enabled the "Only show certain number of latest entries" option, it shows me nothing, when i disabled the option it show me the urls. 

i think somethin gis wrong with this option

ps: could you add an option to get the size from the mpd? because i have an site were are multiple mpd-urls but tweo have the same site (the wrong ones) und one has an different size. i hope you understand this and sorry for my bad english

kev

**Comment by rowrawer** [comment]
Hi, you're right. Looks like the default value doesn't work, but if you change it to any other number it starts working. I'll look into it.

>ps: could you add an option to get the size from the mpd?

I doubt it, as this would involve downloading the file without the user's knowledge, parsing it, etc. - lots of opportunities for something to break. Would be cool but I think I'd rather not risk it.

**Comment by AndroKev** [comment]
thnak you yes you are right if i change it to another value it works:-) only the icon shows the wrong number

> I doubt it, as this would involve downloading the file without the user's knowledge, parsing it, etc. - lots of opportunities for something to break. Would be cool but I think I'd rather not risk it.

okay i thought that you could add the value which the devepoper tool shows
![grafik](https://user-images.githubusercontent.com/3259510/187865721-c25039bd-ee29-46af-b77c-6cc8064ec39e.png)

**Comment by rowrawer** [comment]
The latest entries option should now be working correctly as of v2.10.14.

**Comment by Dean-Corso** [comment]
Hi @rowrawer,

so there is a problem when using / enable the option "Only show certain number of latest entries". In this case only the last X detections are shown in the popup menu what is also the sense of this function of course. Problem is the handling, so I mean lets say I got detected 40 items and my limit to show then is set to 10 then there are still 30 items left & hidden but they are still there. When I now press the button "Clear this URL list" in this tab or all then the visible items gets deleted and the next 10 items gets shown which was hidden before. That means in case of 40 items I have to press 4 times the button "Clear this URL list" to delete them all completely from my lists. So thats of course not so pretty nice you know. Maybe you could adjust this settings when using a limitation. Normally when I wanna use a limitation to log and show the last X items then the rest should be removed from log so that only the last X items are there only you know. Would be maybe better to make it like that. The counter you can keep let count go on of course because all who enabled that feature to log the last X entrys know that just those are logged and no more. Otherwise you could set another button into popup window called "Clear All" to clear really all items from all lists. I would also like to have an settings point to clear all entrys from all lists (all clean) when clsoing or start the browser (similar like to delete cookies when closing) instead of removing entrys which are older than one week. Just some suggestions only. Thanks.

**Comment by rowrawer** [comment]
Hi, thanks for more feedback. This is intentional as the clear URL button should only ever clear visible entries. I don't want to cram more buttons in there but I will consider adding a "clear all entries on browser exit" checkbox to the options.

**Comment by rowrawer** [comment]
The checkbox has now been added in v2.10.17.
