### ISSUE TITLE
Stream detector causing severe start-up delays in Firefox Nightly recently

### ISSUE THREAD

**Issue by LuckySandwich** [rowrawer/stream-detector#18]
I'm using SD 2.1.0 on FF 79 on Linux

When Firefox is started up, it takes at least a minute, maybe even two full minutes, before my tabs load.  I thought this was a Nightly bug, but I narrowed it down to Stream Detector causing the issue. 

Here's an example:

https://i.imgur.com/DKTsk9o.mp4

The example only shows 30 seconds, but it lasts much longer.  This just recently started happening within the last week or so.  

I should also note that it has a cpu core pegged at 100% and I can hear my fan ramped up.  If I close Firefox, the process doesn't die until it's finished doing whatever it's doing.  I have to force kill the process before restarting the browser.

**Comment by rowrawer** [comment]
I downloaded FF 79 and tried to reproduce this, but it works just fine for me. Maybe it's a Linux thing. I can't really think of anything that could cause this - have you tried reinstalling the addon and/or downgrading to an earlier version to see if the issue persists?

**Comment by NessInOnett** [comment]
I just uninstalled/reinstalled it and it seems to have mostly fixed it.. my pinned tabs are loading quick now.  Still having some strange new tab behavior though.. sometimes new tabs refuse to load anything at all.  It could be a conflict with my New Tab Override extension.. I'll dig into it and see.

After extension reinstall, my extension preferences are broken.  I can no longer select some of the options.  Some of the checkboxes and the dropdown list don't work at all, nothing happens when clicked.

Video:

https://i.imgur.com/Zzm4gGq.mp4

**Comment by rowrawer** [comment]
That's weird, looks like your local storage got corrupted somehow - there might be something wrong with your Firefox profile.

If you're feeling up for it, you could clear the storage used by the extension. Go to about:debugging -> This Firefox -> click Inspect next to the addon -> Storage tab -> Extension Storage -> moz-extension:// -> right click anywhere in the table -> Delete all. Turn addon off and on and now the options should work.

**Comment by NessInOnett** [comment]
Thanks for the tip.  I did exactly what you said and the extension options are still broken.  Same problem after clearing the extension storage.

I tested my other extensions and Stream Detector is the only one having this issue.  You'll notice in my 2nd video that the notifications checkbox is also severely delayed.  Sometimes takes 1-2 seconds before the checkmark registers.  

If I rapidly click the notifications checkbox on and off and monitor htop.. the Firefox process ramps up to 100% CPU usage and takes a little while to settle back down.  Something in this extension seems to be hammering the CPU badly.. which could possibly be related to the slow loading times I initially reported.

What a strange issue.

**Comment by rowrawer** [comment]
I had a look around the code and pinpointed a few things that could possibly cause this. I have to make guesses since I can't reproduce it - I doubt it will fix whatever it is that lags the browser on launch since I've no clue why that would happen, but it might fix the delays. I'll upload an update later and you can test it out yourself.

**Comment by NessInOnett** [comment]
Thanks a bunch!  I will test as soon as it's available.  I'll also try a clean Firefox installation and see how that goes.

**Comment by NessInOnett** [comment]
Ok, more testing.. new discovery.  

This seems to be some kind of state management issue.  The way you interact with the extension popup and the extension settings affects whether or not the dropdown box works.

Video: https://i.imgur.com/j7GcN7A.mp4

(_Ignore the fact that the dropdown popup is severely offset... I think that's just because I resized my browser window with the pop-up frozen in place. NOT an issue with SD._)

The dropdown box is completely non-functional in the pop-up **until** I click **one time** on one of the extension settings dropdown boxes.  Then popup dialog starts working again.  If I click a second time on a dropdown box in the extension settings, the dropdown box on the extension pop-up stops working again.

**Comment by rowrawer** [comment]
That seems to be a Nightly thing. Looks like it's bugged in 79, but works just fine in 77. Couldn't really do much about it even if I wanted, it's just basic HTML - I don't really have any control over how the browser displays dropdown lists, I think.

**Comment by SEQUOIIA** [comment]
I'm seeing similar behaviour now with 77.0.1 on Windows. Firefox is stuck loading tabs for a few minutes or until I disable stream detector.

**Comment by rowrawer** [comment]
That's not good. Unfortunately I'm unable to replicate this, so I can't really figure out why this would be happening.

**Comment by Sphinxroot** [comment]
same here ram go up limit and hang pc  so i need to kill firefox  now the plugin is deactivated .. i wonder if its keep in cache all stuff detected .. could be the issues if it keep it in memory on loading . htat explain why the ram get overloaded

**Comment by rowrawer** [comment]
It's kept in the local storage, but that's really nothing - it's just small amounts of text that get parsed almost instantly. I'm guessing something's getting stuck in a loop somewhere.
