### ISSUE TITLE
how to prevent multiple download of the same file?

### ISSUE THREAD

**Issue by airen27** [rowrawer/stream-detector#185]
hello,

so i'm downloading a bunch of mp4 short videos automatically on detection and unfortunately the standard firefox download seems not to have an option to prevent the multiple download of the same file. just renames them (1) (2) …. (99)… 

to acess the short videos i also have to be logged in into my account of the video platform.
so an external downloader that has that feature to prevent doubles didn't work for this and it wouldn't even organize the files into folders as neat as stream detection does.

the detected URL is pretty short like domain.com/fileaccess/f001/f001_03.mp4
so no signature or something, still it is only accessible from within a logged in account in the browser.

so any idea what else i could try?
thanks for your help!

**Comment by rowrawer** [comment]
Hi, unfortunately direct media downloading isn't really filtered much by design - anything that pops up gets grabbed. Can't really implement ignoring files based solely on their name as that could lead to files with generic names being missed, but I'll look into ways of preventing the same files from being redownloaded during the same session at least.

**Comment by rowrawer** [comment]
Auto-downloaded media links are now treated as all other entries as of v2.11.2 once it gets approved by Mozilla - this should prohibit duplicates from being downloaded during the same session.
