### ISSUE TITLE
Request: Add URL as a header

### ISSUE THREAD

**Issue by gothkar** [rowrawer/stream-detector#5]
Would it be possible to add the URL that the m3u8 was pulled from as a header option for youtube-dl and the others? Basically I'd love to have "https://myvideosite.com/video1" added into the command somehow (for post-processing). I love how quick this extension pulls m3u8 playlist URLs, but I'd also love to be able to get the base URL passed in somehow.

**Comment by rowrawer** [comment]
I've considered this, but opted against it as it would make the resulting commands too messy. Any relevant URLs are already included in the commands as part of the Referer header. This is something for future consideration, in case a more detailed list of detected URLs is ever implemented instead of the context menu, I think.
