### ISSUE TITLE
Can you please bring back the old simple menu UI?

### ISSUE THREAD

**Issue by CHJ85** [rowrawer/stream-detector#75]
I've recently switched from Firefox to Brave. Only problem is that the old version 1.9.0 of this addon is not available as a Chrome extension. In my opinion, v1.9.0 is the last good version of the addon because of how nicely put together it is with right click > The Stream Detector to view the links and left click to remove them.
Now on the new versions you have to do all this extra crap.
So do you think you could either go back to the old UI or release a chrome version for v1.9.0 please?
Alternatively on the next version, allow us to switch between the new and the classic UI under Options.

**Comment by rowrawer** [comment]
Sorry, no chance. That stuff is old news. It was a pain to maintain, and the popup menu is a lot nicer to use overall - for me, at least. That being said, anyone is free to fork the project and reimplement the menu system themselves.

**Comment by CHJ85** [comment]
I don't think it's nicer. I think it's annoying. The URLs ain't showing in this new UI and the number of urls doesn't go away from the icon after I clear the URL list. At least in Chrome it doesn't.
Idk how to use a Firefox addon in Chrome. If I knew that, I'd just use the one I have in Firefox.
But how about this for a compromise:
Keep the new UI on left click and add the old UI with the URL list to the right click menu.

**Comment by rowrawer** [comment]
Again, no chance. The whole reason I removed the old menu system was because it was too restrictive and annoying, and I didn't feel like spending my free time maintaining it for no reason if I could switch to a UI solution I liked more instead.

You're listing random bugs from the unsupported Chrome version of the addon. Again, anyone can fork this repo and focus on Chrome or bring back the old menu functionality and maintain it if they want to. Or you could just go back to Firefox - at the end of the day, there's no reason to use Chrome.

**Comment by CHJ85** [comment]
I agree with the last part.
I'm using Brave though. Not Chrome. But it is Chromium based.
I didn't realize that the chrome version is unsupported. But that would certainly explain it.
But if it doesn't work, why do you include the crx file?
Are there any working versions of the Chrome extension that you know of?

**Comment by rowrawer** [comment]
It's only included here on GitHub because a bunch of people asked for it and the crx file doesn't take long to make. It used to work just fine, I think a Chrome update broke it. I'll look into patching it up sometime. That being said, I should probably put up some sort of clearly visible disclaimer somewhere about the Chrome version not being supported.

**Comment by CHJ85** [comment]
Thanks for your quick responses. I really appreciate it.
What are your steps for turning the Firefox addon into a Chrome extension? Because maybe I can make the 1.9.0 version work on Chrome.

**Comment by rowrawer** [comment]
This was discussed here:
https://github.com/rowrawer/stream-detector/pull/34

Theoretically if you extract the xpi file of the old version (e.g. rename to .zip), do the steps outlined in the pull request, and then load an unpacked extension in Chrome, it should work, unless there was some Firefox-specific code in that version.

**Comment by CHJ85** [comment]
Okay thank you!

**Comment by CHJ85** [comment]
I tried but had to give it up.
There are just too many errors and it's not even detecting the streams.

**Comment by USvsTHEM** [comment]
rowrawer if i fork the android beta or nightly how do i bring back the old unscrollable menu you selfishly jacked up the ui/ux instead of thi king about the collective if.you gonna keep it scrolkable which makes no sense add the settings button up tol since that is what most people hit the 3dot hamburger for anyway settings bookmark or collection or make the order of settings more logical you have the most important option in this fugazzy menu hidden the farthest total deal breaker man if it aint broke dont fix it

**Comment by Mrnofish** [comment]
> Now on the new versions you have to do all this extra crap.
> the old unscrollable menu you selfishly jacked up the ui/ux 

You guys need to work on your manners.

This kind of behavior is partly responsible for people dropping out of FOSS projects. Not only they contribute their work for free to the community, as a bonus they get to deal with smugness, entitlement and plain rudeness.

And if you think harassing, insulting and alienating people will make them more likely to do as you please, think again because it's quite the opposite.

Thanks @rowrawer for all your work and please excuse these two characters. You've been way more patient and helfpul than of any of them deserved. Kudos!

**Comment by CHJ85** [comment]
@Mrnofish Facts! What that guy said was uncalled for.
