### ISSUE TITLE
Save to File

### ISSUE THREAD

**Issue by BMOC1** [rowrawer/stream-detector#87]
I apologize ahead of time if this already exists.  I just cannot figure it out for the life of me and I don't see a help guide here.

I think this add on is brilliant.  

It would be terrific if an option existed that would automatically write the HLS/M3U links to an appending file or unique file etc.  I wouldn't need to do anything other then load the web page in my browser.  - I would then see the text file in the download path.

Thank U

**Comment by nkomarov** [comment]
There are currently options on the plugin page related to direct file saving but it's not clear how to enable them. These checkboxes are simply disabled. And there is no hint on how to enable them. If it's not implemented you could add a tooltip declaring that. If it is, a tooptip explaining how to enable would be useful to have.

**Comment by rowrawer** [comment]
Direct file saving can be enabled by checking the "download files instead of copying their URLs", which is available if "ignore direct links to video/audio files" is unchecked. Then the "automatically download files" option becomes available if you so desire, or you could use the popup menu as always. Seems quite logical to me.
